### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by ggl** [ingydotnet/pegex-crontab-pm#2]
Doesn't work. It inherits from Pegex::Module allright but it fails to initialize parser_class => Pegex::Parser for some reason.

```
#!/usr/bin/env perl

use strict;
use warnings;

use Pegex::Crontab;
use IO::All;
use Data::Dumper;

my $json = io("crontab")->slurp;
my $data = Pegex::Crontab->parse($json);
print Dumper $data;
```

Can't call method "new" on an undefined value at /home/gelu/perl5/lib/perl5/Pegex/Module.pm line 16

**Comment by ingydotnet** [comment]
Should be working now.
